ID: 5
cuda: true
env.id: HalfCheetah-v2
env.standardize: true
network.recurrent: true
network.hidden_sizes:
- 32
algo.lr: 0.001
algo.use_lr_scheduler: false
algo.gamma: 0.99
agent.standardize_Q: false
agent.standardize_adv: false
agent.max_grad_norm: 0.5
agent.entropy_coef: 0.01
agent.value_coef: 0.5
agent.min_std: 1.0e-06
agent.std_style: exp
agent.constant_std: null
agent.std_state_dependent: false
agent.init_std: 0.5
train.timestep: 1000000.0
train.N: 5
train.T: 5
eval.N: 100
log.record_interval: 100
log.print_interval: 500
log.dir: logs
