ID: 6
cuda: true
env.id: HalfCheetah-v2
env.standardize: true
network.recurrent: false
network.hidden_sizes:
- 64
- 64
algo.lr: 0.0007
algo.use_lr_scheduler: true
algo.gamma: 0.99
algo.gae_lambda: 0.97
agent.standardize_Q: false
agent.standardize_adv: true
agent.max_grad_norm: 0.5
agent.entropy_coef: 0.01
agent.value_coef: 0.5
agent.fit_terminal_value: true
agent.terminal_value_coef: 0.1
env.clip_action: true
agent.min_std: 1.0e-06
agent.std_style: exp
agent.constant_std: null
agent.std_state_dependent: false
agent.init_std: 0.8
train.timestep: 1000000.0
train.N: 1
train.ratio_T: 0.2
eval.independent: true
eval.N: 10
log.record_interval: 100
log.print_interval: 100
log.dir: logs_init_stds
