ID: 0
cuda: true
env.id: HalfCheetah-v2
env.standardize: true
network.recurrent: false
network.hidden_sizes:
- 64
- 64
network.independent_V: true
algo.lr: 0.0003
algo.lr_V: 0.001
algo.use_lr_scheduler: true
algo.gamma: 0.99
algo.gae_lambda: 0.97
agent.standardize_Q: false
agent.standardize_adv: true
agent.max_grad_norm: 0.5
agent.entropy_coef: 0.0
agent.value_coef: 0.5
agent.fit_terminal_value: true
agent.terminal_value_coef: 0.1
agent.clip_range: 0.2
agent.target_kl: 0.015
env.clip_action: true
agent.min_std: 1.0e-06
agent.std_style: exp
agent.constant_std: null
agent.std_state_dependent: false
agent.init_std: 0.5
train.timestep: 1000000.0
train.N: 2
train.ratio_T: 1.0
eval.independent: false
eval.N: 10
train.batch_size: 256
train.num_epochs: 80
log.interval: 10
log.dir: logs.network.independent_V
